name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}

      - name: Pull `unmanaged` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged

      - name: Pull `worlds` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/worlds
          token: ${{ secrets.PAT }}
          path: worlds

      - name: Pull `collections` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/collections
          token: ${{ secrets.PAT }}
          path: collections

      - name: Pull `types` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/types
          token: ${{ secrets.PAT }}
          path: types

      - name: Pull `rendering` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/rendering
          token: ${{ secrets.PAT }}
          path: rendering

      - name: Pull `simulation` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/simulation
          token: ${{ secrets.PAT }}
          path: simulation

      - name: Pull `shaders` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/shaders
          token: ${{ secrets.PAT }}
          path: shaders

      - name: Pull `meshes` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/meshes
          token: ${{ secrets.PAT }}
          path: meshes

      - name: Pull `serialization` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/serialization
          token: ${{ secrets.PAT }}
          path: serialization

      - name: Pull `data` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/data
          token: ${{ secrets.PAT }}
          path: data
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Build Source
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Release

      - name: Pack Source
        run: dotnet pack "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION} --no-build --output .

      - name: Add source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
      
      - name: Push Source
        run: dotnet nuget push Windows.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}