name: Test

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '.github/workflows/test.yml'
    branches:
      - main
      - dev
      - dev/**

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}

      - name: Pull `unmanaged` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged

      - name: Pull `worlds` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/worlds
          token: ${{ secrets.PAT }}
          path: worlds

      - name: Pull `collections` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/collections
          token: ${{ secrets.PAT }}
          path: collections

      - name: Pull `types` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/types
          token: ${{ secrets.PAT }}
          path: types

      - name: Pull `rendering` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/rendering
          token: ${{ secrets.PAT }}
          path: rendering

      - name: Pull `materials` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/materials
          token: ${{ secrets.PAT }}
          path: materials

      - name: Pull `shaders` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/shaders
          token: ${{ secrets.PAT }}
          path: shaders

      - name: Pull `textures` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/textures
          token: ${{ secrets.PAT }}
          path: textures

      - name: Pull `meshes` dependency
        uses: actions/checkout@v4.1.2
        with:
          repository: game-simulations/meshes
          token: ${{ secrets.PAT }}
          path: meshes
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Debug --logger "trx"

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          working-directory:  ${{ github.event.repository.name }}
          name: Report
          path: 'tests/TestResults/*.trx'
          reporter: dotnet-trx
          fail-on-error: false